### ISSUE TITLE
YTuner not working on OpenWRT

### ISSUE THREAD

**Issue by rkerschn** [coffeegreg/YTuner#37] opened 2024-11-13 19:44 UTC
Dear Greg,

I've just tried to get YTuner running on my R7800 running OpenWRT.

First I made the ytuner executable with chmod +x

Nevertheless, executing YTuner always leads to:
-bash: ./ytuner  not found

i digged a bit deeper and I think its an issue with the loader.

According to the OpenWRT HDDB the R7800 has the following Architecture:
ARMv7 Processor rev 0 (v7l), arm_cortex-a15_neon-vfpv4

Regards, Reinhard

**Comment by rkerschn** [comment] 2024-11-13 22:04
Hi Greg,

To be honest, I never manually ran an application on OpenWRT, but only used the packaging tool opkg. But it should work as with any other Linux Distro.

May I ask, where have you found the libraries for Linux_ARM_OpenWrt_2203? I would need 2305.

`router:/etc/ytuner# chmod +x ytuner`
`router:/etc/ytuner# ./yutner`
`-ash: ./yutner: not found`
`router:/etc/ytuner# ldd ytuner`
`        /lib/ld-linux-armhf.so.3 (0xb6f25000)`
`        libpthread.so.0 => /lib/ld-linux-armhf.so.3 (0xb6f25000)`
`        libdl.so.2 => /lib/ld-linux-armhf.so.3 (0xb6f25000)`
`        librt.so.1 => /lib/ld-linux-armhf.so.3 (0xb6f25000)`
`        libc.so.6 => /lib/ld-linux-armhf.so.3 (0xb6f25000)`

So I had a look at /lib and only found  the ld-musl-armhf.so.1 library

All in all, sounds awesome, I help where I can.

**Comment by rkerschn** [comment] 2024-11-13 23:02
I have tried to manually install libpthread, libdl and librt but
it looks like the library `libdl` is missing in the repository

I will check on that and will let you know

**Comment by TheBossME** [comment] 2024-11-14 09:17
One question: which version of openwrt is running ?

**Comment by rkerschn** [comment] 2024-11-14 09:25
Dear Beatrice,

yep, I am running 2305.
That would be great if you could check it as well, thank you :)

**Comment by TheBossME** [comment] 2024-11-14 09:31
> Dear Beatrice,
> 
> 
> 
> yep, I am running 2305.
> 
> That would be great if you could check it as well, thank you :)

https://downloads.openwrt.org/releases/22.03.5/targets/armvirt/64/ 

This is the one I can actually checkout. 
If this this to much different, it wouldn't help.

**Comment by rkerschn** [comment] 2024-11-14 09:39
you could use this, armsr replaces armvirt, according to 23.05 releasenotes
https://downloads.openwrt.org/releases/23.05.5/targets/armsr/armv7/

Release notes of 23.05 (https://openwrt.org/releases/23.05/notes-23.05.0):

**Highlights of device support**
Added Arm SystemReady (EFI) compliant target armsr replacing the armvirt target

**Comment by TheBossME** [comment] 2024-11-14 09:57
Okay.. I do love Proxmox .. 

https://downloads.openwrt.org/releases/23.05.5/targets/armsr/armv8/openwrt-23.05.5-armsr-armv8-generic-ext4-combined.img.gz

Is running.. I will go forward to configure..

![image](https://github.com/user-attachments/assets/ac34c5f7-ab45-4fc4-ad44-45f794a14c43)

**Comment by rkerschn** [comment] 2024-11-14 10:00
Great work, looks good!

Are you running arm v8 or v7?

The link in your last posting is arm v8,
The router I am running is arm v7

**Comment by TheBossME** [comment] 2024-11-14 10:04
> Great work, looks good!
> 
> 
> 
> Are you running arm v8 or v7?
> 
> 
> 
> The link in your last posting is arm v8,
> 
> The router I am running is arm v7

I can use both.

**Comment by rkerschn** [comment] 2024-11-14 10:05
I see, thanks

**Comment by rkerschn** [comment] 2024-11-14 10:52
this is the package that I used:
ytuner-1.2.3-arm-linux.zip

**Comment by TheBossME** [comment] 2024-11-14 11:08
> this is the package that I used:
> 
> ytuner-1.2.3-arm-linux.zip

What operating system is behind openwrt ?
If based on alpine Linux, the See my prior postings about installing missed compatibility libraries.

Greg: I informed in my last postings regarding alpine Linux.
Please put this information into documentation. Thanks.

**Comment by rkerschn** [comment] 2024-11-14 11:15
It's not based on Alpine but like Alpine, it uses BusyBox and musl.

About missing libraries, yep, that's what I mentioned yesterday.

> I have tried to manually install libpthread, libdl and librt but it looks like the library `libdl` is missing in the repository
> 
> I will check on that and will let you know

**Comment by rkerschn** [comment] 2024-11-14 11:37
from [Wikipedia](https://en.wikipedia.org/wiki/OpenWrt):
OpenWrt (from open wireless router) is an open-source project for [embedded operating systems](https://en.wikipedia.org/wiki/Embedded_operating_system) based on [Linux](https://en.wikipedia.org/wiki/Linux_kernel), primarily used on [embedded devices](https://en.wikipedia.org/wiki/Embedded_system) to [route](https://en.wikipedia.org/wiki/Router_(computing)) network traffic. The main components are Linux, [util-linux](https://en.wikipedia.org/wiki/Util-linux), [musl](https://en.wikipedia.org/wiki/Musl),[[4]](https://en.wikipedia.org/wiki/OpenWrt#cite_note-4) and [BusyBox](https://en.wikipedia.org/wiki/BusyBox). All components have been optimized to be small enough to fit into the limited storage and memory available in home routers.

OpenWrt is configured using a [command-line interface](https://en.wikipedia.org/wiki/Command-line_interface) ([ash](https://en.wikipedia.org/wiki/Almquist_shell) shell) or a web interface (LuCI). There are about 8000 optional [software packages](https://en.wikipedia.org/wiki/Software_package_(installation)) available for installation via the [opkg](https://en.wikipedia.org/wiki/Opkg) [package management system](https://en.wikipedia.org/wiki/Package_management_system).

**Comment by TheBossME** [comment] 2024-11-14 11:43
Have you installed bash for starting ytuner ? And what about the missed c-libs ?. There is no compile for openwrt needed. 

If you are using such exotic hardware, support will end here.

**Comment by rkerschn** [comment] 2024-11-14 11:56
Thanks for your effort giving it a try.
Could you try OpenWRT i386 with ytuner i386 with Proxmox?

I would say ARM is ARM, no matter - so I think the issue is not necessarily the hardware rather than the software (OS).
Compiling for OpenWRT would take care of such dependencies.

**Comment by TheBossME** [comment] 2024-11-14 12:07
Nope.

You can install free pascal on your openwrt system and compile yourself, or using supported distros. 

Greg told you: He has not all hardware available to test. 

Proxmox is designed for 64 bit systems only.

**Comment by rkerschn** [comment] 2024-11-14 12:17
@TheBossME 
If you are not able to contribute anymore, thats fine with me.
Thank your effort and time so far!

I think it is perfectly legitimate to ask for support for a further distribution.
Especially because it makes a lot of sense to have ytuner running on the home router, that needs to run anyway. So no other hardware that acts as a server is needed to run in addition.

**Comment by TheBossME** [comment] 2024-11-14 12:28
> @TheBossME 
> 
> If you are not able to contribute anymore, thats fine with me.
> 
> Thank your effort and time so far!
> 
> 
> 
> I think it is perfectly legitimate to ask for support for a further distribution.
> 
> Especially because it makes a lot of sense to have ytuner running on the home router, that needs to run anyway. So no other hardware that acts as a server is needed to run in addition.
> 
> 

Agreed 👍 
Keep in mind. Greg has not the ability (not all hardware available) and time to compile on different platforms.

Again: Feel free to install Free Pascal on your hardware and start compile. I have no Pascal knowledge.

Installing I386 OS'SES is possible to install. But this will not help you as I understand right ?.

My other plan is, installing ytuner cluster instances for everybody with a default configuration. Will this be helpful for ya ?

**Comment by rkerschn** [comment] 2024-11-14 13:34
> Keep in mind. Greg has not the ability (not all hardware available) and time to compile on different platforms.

I think that's up to Greg. As I understood in his reply here, he suggested to give it a try, but he needs my help for testing. I am looking forward to help where I can :)

> Again: Feel free to install Free Pascal on your hardware and start compile. I have no Pascal knowledge. 

me neither, I also have no Pascal knowledge 

> Installing I386 OS'SES is possible to install. But this will not help you as I understand right ?.

It would help to see if it is a hardware or software related issue.
I've just tested it via kvm qemu i386 OpenWRT --> same issue as with arm7

> My other plan is, installing ytuner cluster instances for everybody with a default configuration. Will this be helpful for ya ?

I don't know but I would expect some difficulties regarding copyright due to the vtuner API. I would prefer a solution running privately on my own hardware. Nevertheless, I appreciate your offer, thank you!

**Comment by TheBossME** [comment] 2024-11-14 13:40
Finally: It is library issue.

If free pascal has no compile option for the needed library, it will not run.

Schönen Nachmittag 
Gruß Beatrice

**Comment by rkerschn** [comment] 2024-11-14 13:51
it's weird, because `ldd` does not give any hint about a missing library ;)

**Comment by TheBossME** [comment] 2024-11-14 14:33
Ist es nicht, definitiv fehlen die zur Ausführung der Application nötigen libraries (gcompat z.b.). Bitte versuch die alpine repository hinzuzufügen eventuell kannst Du diese von dort installieren.

**Comment by rkerschn** [comment] 2024-11-14 15:28
Dear Beatrice,

I have tried as you suggested, for testing purpose, but I get an `UNTRUSTED signature` error.
Nevertheless, adding a non OpenWRT repository is not an option on a productive system, especially edge systems like routers. That would break the whole upgrade process. The only clean solution would be to build ytuner considering OpenWRT requirements.

As I said, I think it is perfectly legitimate to ask for support for a further distribution.
It is fine for me that you use alpine linux, but please respect that alpine is not the ultimate solution for everyone. Other purposes, other requirements, other demands, etc...

I appreciate your effort, but I am counting on @coffeegreg Greg and that I am going to support him in any way possible for me.

**Comment by coffeegreg** [comment] 2024-11-14 16:48
I wrote a message here yesterday and went to sleep. This morning I went to work and just got back and I see ... 25 new messages. :eyes:  You have not been idle ... :+1: 
I will not reply to each one of them .. it would probably take me the whole rest of the day. :wink: 

@rkerschn :
> Would it be possible to compile it for OpenWRT as well ...

Yes, This is what I'm going to try. :+1: 

> It would make a lot of sense to have ytuner running on the home router, that needs to run anyway. So no other hardware needs to run in addition.

Yes, it is.

>I think it is perfectly legitimate to ask for support for a further distribution.

Agree.

>Especially because it makes a lot of sense to have ytuner running on the home router, that needs to run anyway. So no other hardware that acts as a server is needed to run in addition.

Agree ... but :thinking: ... some functionality that requires or will require more CPU computing power may not work properly.

> I would say ARM is ARM, no matter in wihch device it is soldered ...

That's not entirely true ...

>I think that's up to Greg. As I understood in his reply here, he suggested to give it a try, but he needs my help for testing. I am looking forward to help where I can :)

Great :exclamation: :rocket: 

> I don't know but I would expect some difficulties regarding copyright due to the vtuner API.

In the case of YTuner, there can be no question of violating any copyrights. No one stole anything from anyone and did no reverse engineering on it. The implemented YTuner functionality is based on the analysis of network traffic to/from AVR. That's all, everything in accordance with the law.

>It is fine for me that you use alpine linux, but please respect that alpine is not the ultimate solution for everyone. Other purposes, other requirements, other demands, etc...

Agree.

@TheBossME :
>You can install free pascal on your openwrt system and compile yourself, or using supported distros.

I'm afraid that wouldn't be easy if at all possible. That's why freepascal can compile for other OSs and CPU arch.

>Keep in mind. Greg has not the ability (not all hardware available) and time to compile on different platforms.

Compiling is not the problem, just testing it on a real platform.

> Greg told you: He has not all hardware available to test.

True. :disappointed: 

> My other plan is, installing ytuner cluster instances for everybody with a default configuration.

ABSOLUTELY FANTASTIC IDEA :exclamation: :exclamation: :rocket: :clap: 
This would require additional changes on YTuner's part. For example, moving some options to the `avr.ini` equivalent so that everyone has their own settings and adding a web management panel and ... some other things ... :thinking:  
Who will pay for maintaining the service? :wink: 

I have to go now... I'll add the rest when I get back. Why does a day only have 24 hours? :thinking:  :wink:

**Comment by coffeegreg** [comment] 2024-11-14 21:10
I checked. Good news: FPC can compile to ARM/OpenWRT. :+1: 
Bad news. There is no dedicated "profile" for such a configuration and it overlaps with the current ARM/Linux (proper for e.g. RPI).
I need to figure out how to add a new profile for ARM/OpenWRT without overwriting the current ARM/Linux and run tests on a new VM. :thinking:  It will take some time and I don't have much free time right now.
I'll try to do something over the weekend. I'll let you know when I find out something and check it. Stay tuned...

**Comment by coffeegreg** [comment] 2024-11-15 16:44
First, let's start with some simple test and the "Hello Word" application to check if the simplest application generated with my 22.03 libraries will run on OpenWRT.
Here it is :
[hello_world_1.zip](https://github.com/user-attachments/files/17778500/hello_world_1.zip)

@rkerschn :
Please try to run this on your router

@TheBossME :
Can you try to run this on your fabulous Proxmox VE? :+1: 

Don't forget about `chmod +x` :wink:

**Comment by rkerschn** [comment] 2024-11-15 20:48
Hi Greg,
sorry for my late reply, had a quite busy day.

Thanks for your replay yesterday and that you want to give it a try with OpenWRT.

> Agree ... but 🤔 ... some functionality that requires or will require more CPU computing power may not work properly.
Thats a valid point, since many home routers are lacking CPU power and RAM. Mine is a Netgear R7800, having 128MB Flash ROM, 512MB RAM and a Qualcomm Atheros IPQ8065, Arm v7, 1.7GHz, with 2 cores. That should be sufficient for YTuner.

> I'm afraid that wouldn't be easy if at all possible. That's why freepascal can compile for other OSs and CPU arch.
Yep, that's true. Free Pascal can not be installed on OpenWRT. Not even thinking about compiling on that embeded System.

> I checked. Good news: FPC can compile to ARM/OpenWRT. 👍

Thats awesome 🤩

> Bad news. There is no dedicated "profile" for such a configuration and it overlaps with the current ARM/Linux (proper for e.g. RPI).
No Good News without any Bad News, but I hope you can find a solution for that.

> I need to figure out how to add a new profile for ARM/OpenWRT without overwriting the current ARM/Linux and run tests on a new VM. 🤔 It will take some time and I don't have much free time right now.

No worries, you also have a live, so please take your time 🙂

**Comment by coffeegreg** [comment] 2024-11-15 21:33
@rkerschn 
Please test the two "Hello World" apps I have attached earlier.

**Comment by rkerschn** [comment] 2024-11-15 22:16
@coffeegreg 
both "Hello World" apps work.

**Comment by coffeegreg** [comment] 2024-11-15 22:42
Now I'm trying to build YTuner with my 22.03 libraries but I'm facing problems building for ARMHF. :thinking: 
That's enough for today. :sleeping: I live in the UTC+01 time zone.

**Comment by rkerschn** [comment] 2024-11-15 22:44
Do you also have libs for OWrt 23.05? That's the latest stable.

Thanks for you effort, have a good night 🙂

**Comment by coffeegreg** [comment] 2024-11-16 20:50
@rkerschn 
I built another binary for the "Hello World" application using the same libraries and the cross-compiler that I use to build ytuner binaries. 
The "Hello World" application binaries were exactly the same as the ones I sent here yesterday and which I generated using the OpenWRT 22.03 libraries and the cross-compiler dedicated to Linux musl. I'm not surprised because the YTuner binaries that I built so far worked on arm and Alpine Linux, which, like OpenWRT, is a linux distribution that uses musl as their standard C library. So what's the problem that you can't run YTuner on your R7800? :thinking: 
Maybe it's really a matter of libraries, although as you confirmed, the simple "Hello World" application started. However, YTuner is more complicated than "Hello World" and requires additional libraries to run. To compile and build the binaries themselves, the libraries are needed to check their entries and dependencies. Therefore, an application built using libraries from the old Fedora will also work on the new Ubuntu and it probably doesn't matter whether I'll build the application using OpenWRT 22.03 or 23.05 libraries. Nevertheless, the problem is still unresolved...
In Alpine Linux (musl), to run an application created in Free Pascal, we need the `libc6-compat` or `gcompat` library (Beatrice mentioned about this) and YTuner works on Alpine Linux (at least on the x86 platform that I tested and probably aarch64 (arm64) that Batrice tested) but...  in OpenWRT there is already `libc.so` as a link to `ld-musl-armhf.so.1` and a simple "Hello World" starts. :thinking: Either there is a problem with the libraries on the OpenWRT side or the problem concerns the ARMHF and VFP platform itself, but then the error message would probably be different and not a laconic "not found". :thinking: ... but maybe I'm wrong ... :thinking: 
Try this :
`file ./ytuner`
and let's compare this with
`file /bin/echo`
:thinking: 
Lack of a suitable dynamic linker often leads to confusing "file not found" and "this is not a dynamic executable" style messages. :thinking: Does `/lib/ld-linux.so.3` exist on your system? If not try to make link to `ld-linux-armhf.so.3` :
`sudo ln -s /lib/ld-linux-armhf.so.3 /lib/ld-linux.so.3`
and run YTuner.
Please try to use attached libraries (OpenWRT 23.05) :
[openwrt-23.05.0-armsr-armv7.zip](https://github.com/user-attachments/files/17787871/openwrt-23.05.0-armsr-armv7.zip)
or better install them from the proper packages. With some configuration, YTuner also uses libraries `libsqlite3`, `libssl` and `libcrypto` .
The problem is related to my lack of knowledge of OpenWRT and I don't know what I really need to run applications created in GCC or FPC. :disappointed: 
I will also try to build an alternative environment to support ARMHF and try to check what the compiler will generate or... try to build to use soft FPU ... :thinking: 
You can try to build a VM with QEMU with exactly the same configuration as for `arm_cortex-a15_neon-vfpv4` and temporarily upload it to `file.io` for example. It will make testing easier for me.
I can't think of anything better at the moment... maybe when I sleep at night my brain will come up with a better idea ... :wink:

**Comment by rkerschn** [comment] 2024-11-18 15:02
Dear Greg,

I trying to get a kvm qemu armv7 instance running on a x86_64 system. It's quite challenging to change the architecture for an emulation. I will let you know as soon as I succeed.
In principle this image should work:
https://downloads.openwrt.org/releases/23.05.5/targets/armsr/armv7/openwrt-23.05.5-armsr-armv7-generic-ext4-combined.img.gz

I assume that if it is a library issue, we could test it using this image, since the libraries included in the system should be the same.

**Comment by rkerschn** [comment] 2024-11-18 15:48
I had to install `qemu-system-arm` and `qemu-system-arm-core` to get armv7 emulation option in the virtual machine manager.
Within the machine config I could choose cortex-a15, set up 512GB RAM, 1GiB of hdd storage.
Once I have started up the image, the machine is running as `arm-cortex-a15-neon-vfpv4`

this guided helped me a lot with the configuration of :
https://blog.thomas.maurice.fr/posts/virtualise-openwrt/

**Comment by coffeegreg** [comment] 2024-11-18 15:49
@rkerschn
Before you prepare QEMU VM ... did you try this :
`ln -s /lib/ld-linux-armhf.so.3 /lib/ld-musl-arm.so.3`
or this :
`ln -s /lib/ld-linux-armhf.so.3 /lib/ld-linux.so.3`
as I described earlier ? :thinking:

**Comment by rkerschn** [comment] 2024-11-18 15:50
I am going to try it within the VM, so not to risk anything on my router.

**Comment by coffeegreg** [comment] 2024-11-18 15:52
It's not risky.. it's just a link. Try it.
I have a feeling this will help ...

**Comment by coffeegreg** [comment] 2024-11-18 16:12
> creating the symbolic links did not help

I found a similar case with OpenWRT described on the internet. It helped there... unfortunately not in your case.
It must be a missing library or a problem with the dynamic linker. :thinking:

**Comment by rkerschn** [comment] 2024-11-18 16:12
the other way round did the trick:
ln -s /lib/ld-musl-armhf.so.1 /lib/ld-linux-armhf.so.3

so it looks like that the compiled ytuner does link to the wrong library.
Could this be changes in fpc?

**Comment by coffeegreg** [comment] 2024-11-18 16:15
I wrote about :
```
/lib/ld-linux-armhf.so.3 (0xb6f25000)
        libpthread.so.0 => /lib/ld-linux-armhf.so.3 (0xb6f25000)
        libdl.so.2 => /lib/ld-linux-armhf.so.3 (0xb6f25000)
        librt.so.1 => /lib/ld-linux-armhf.so.3 (0xb6f25000)
        libc.so.6 => /lib/ld-linux-armhf.so.3 (0xb6f25000)
```
We can see `ld-linux-armhf.so.3`
I've to go right now.

**Comment by coffeegreg** [comment] 2024-11-18 16:16
There is already some service listening on TCP port 80
I've to go ..............

**Comment by rkerschn** [comment] 2024-11-18 16:24
```
router:/etc/ytuner# ldd ytuner
        /lib/ld-linux-armhf.so.3 (0xb6f25000)
        libpthread.so.0 => /lib/ld-linux-armhf.so.3 (0xb6f25000)
        libdl.so.2 => /lib/ld-linux-armhf.so.3 (0xb6f25000)
        librt.so.1 => /lib/ld-linux-armhf.so.3 (0xb6f25000)
        libc.so.6 => /lib/ld-linux-armhf.so.3 (0xb6f25000)
```

Yep, I also thought that if it is not present, than ldd should say `missing`. Looks like that it is the other way round 🤪
so `ldd` sees that ytuner is expecting `/lib/ld-linux-armhf.so.3`
But in /lib/ there is only `ld-musl-armhf.so.1`

Nevertheless, this does the trick, so I assume for openwrt fpc should link to /lib/ld-musl-armhf.so.1 instead of /lib/ld-linux-armhf.so.3

>I've to go ..............

No worries, have a nice evening

**Comment by coffeegreg** [comment] 2024-11-18 20:37
> So from the above mentioned findings, we do not need these libraries: libc6-compat or gcompat, the already existing (in Alpine as well as in OpenWrt) libc is enough.

I disagree. Look at my docker [tutorial](https://github.com/coffeegreg/YTuner/blob/master/doc/DOCKER.md) based on Alpien Linux image.

> I assume that FPC sets non or a wrong path and/or filename where ytuner expects the libraries.

No. FPC is based on a set of libraries (Linux distr., Solaris, FreeBSD, FreeBSD, OpenBSD, MacOS etc) provided to it. In my case, from Fedora or Ubuntu, Solaris, FreeBSD .... As I wrote earlier ... FPC
> ....check their entries and dependencies...

and builds binaries for selected OSs based on this knowledge. Most Linux distributions are compatible with default libraries but `musl` Linux distributions based on busybox are different (Alpine Linux, OpenWRT). In such cases, however, it is enough to make a valid link to dynamic linker and be sure to have `libc6-compat` or `gcompat` or just `libc` in your case because OpenWRT, is a linux distribution that uses `musl` as their standard C library, not libc expected to run FPC binaries.

If I understood correctly, in your case the following link helped: 
`ln -s /lib/ld-musl-armhf.so.1 /lib/ld-linux-armhf.so.3`
Are you sure ?
Ther is a code :
```
{$IFDEF UNIX}
// At this moment I have no better idea how to detect Alpine Linux Busybox ?
// ! In this case, enter the YTuner directory first and then run it with ./ytuner !
  if ParamStr(0).Contains('ld-musl-') then
    Result:='./'
  else
{$ENDIF}
    Result:=ProgramDirectory;
```
Maybe in case of OpenWRT I need to add also 'ld-linux-' ... :thinking: Without the correct result of the above function, the Tuner may not work properly.

Finally, I'm glad to know that YTuner start on OpenWRT :+1:  but ... as you can see ... You have to take care about correct YTuner configuration (grant access to TCP port 80 (web service) and UDP port 53 (DNS service - optional) or run on another interface)
One piece of good advice : Please read very carefully the ENTIRE `ytuner.ini` and `avr.ini` files included with the binaries. There are many options that will help you configure the YTuner to work the way you want it to.

**Comment by rkerschn** [comment] 2024-11-18 20:54
>>So from the above mentioned findings, we do not need these libraries: libc6-compat or gcompat, the already existing (in >>Alpine as well as in OpenWrt) libc is enough.

>I disagree. Look at my docker [tutorial](https://github.com/coffeegreg/YTuner/blob/master/doc/DOCKER.md) based on >Alpine Linux image.

the gcompat library works, because it provides glibc compatibility (as the name gcompat suggests) for musl  libc systems.
Fact is, because I have verified it with Alpine Linux and OpenWrt, you can achieve the same thing with a symbolic link to the correct runtime linker.

Why the symbolic link does work is explained in my previous post. its because of the .interp ELF header.
gcompat does the same thing.

I assume, would YTuner be compiled for musl libc instead of glibc, the .interp would change to the correct runtime linker ld-musl-armhf.so.1

If you have an Alpine machine running, even on a KVM Qemu VM, you could verify it yourself by adding a symbolic link.
Adding a symbolic link to ld-musl-armhf.so.1 was your own idea and you where right with it 😉

**Comment by rkerschn** [comment] 2024-11-18 21:04
> There is already some service listening on TCP port 80 I've to go ..............

The picture in my posting above( https://github.com/coffeegreg/YTuner/issues/37#issuecomment-2483492769)
I wanted to show that YTuner works on OpenWrt as expected.
Just ignore the port 80 error, that's LUCI (OpenWrt Web Interface) listening on Port 80.
The important thing is that it works on OpenWrt when linked to the correct musl runtime linker via the symbolic link.

NO additional libraries like gcompat, etc... are required, i've confirmed it on OpenWrt and Alpine Linux.

ld-musl-armhf.so.1 is also nothing else than a symbolic link to /lib/libc.so

**Comment by coffeegreg** [comment] 2024-11-18 21:06
> I assume, would YTuner be compiled for musl libc instead of glibc ....

I'm not sure if that's even possible... I don't know FPC that well.

> If you have an Alpine machine running, even on a KVM Qemu VM, you could verify it yourself by adding a symbolic link.

I don't have it ... and not much free time either. :wink: I prefer to spend it coding new features in YTuner. A few more interesting ideas to implement... :+1:

**Comment by coffeegreg** [comment] 2024-11-18 21:12
> NO additional libraries like gcompat, etc... are required, i've confirmed it on OpenWrt and Alpine Linux.

:thinking: ... Beatrice @TheBossME ... What do you think about this? :wink:

**Comment by rkerschn** [comment] 2024-11-18 21:12
> > The problem is, that this runtime linker is not available on Alpine Linux or OpenWrt. Those two distributions use a different runtime linker called ld-musl-armhf.so.1
> 
> Correct. I thought you had `so.3` file. (runtime linker = dynamic linker)
> 
> Please try to run another test program : [test1.zip](https://github.com/user-attachments/files/17806132/test1.zip)
> 
> This will tell me if any changes to the code are needed.
> 
> Once you have placed in your file system all the required files provided with the YTuner 1.2.3 zip archive and configure all settings you can try the new `YTuner 1.2.4 beta 1` : [#32 (comment)](https://github.com/coffeegreg/YTuner/discussions/32#discussioncomment-11285151)

I have just tested your test1.zip

ELF .interp header is again **`/lib64/ld-linux-x86-64.so.2`**
Meaning, it gives the same **`not found `** error

Only when adding the symbolic link as follows:
ln -s /lib/ld-musl-armhf.so.1 /lib64/ld-linux-armhf.so.3
it works

**Comment by coffeegreg** [comment] 2024-11-18 21:14
> I have just tested your test1.zip

I need to know what it printed on the console... :wink:

**Comment by rkerschn** [comment] 2024-11-18 21:15
![Screenshot_20241118_185005](https://github.com/user-attachments/assets/25a40fb5-ae2f-44dc-9243-67c031567035)

> > NO additional libraries like gcompat, etc... are required, i've confirmed it on OpenWrt and Alpine Linux.
> 
> 🤔 ... Beatrice @TheBossME ... What do you think about this? 😉

This screenshot (quoted from above) is the proof that you do not need the libraries.

![Screenshot_20241118_185005](https://github.com/user-attachments/assets/25a40fb5-ae2f-44dc-9243-67c031567035)

**Comment by rkerschn** [comment] 2024-11-18 21:16
> > I have just tested your test1.zip
> 
> I need to know what it printed on the console... 😉

```
Test 1...
/etc/test1
Test 2...
/etc/
Done.
```

**Comment by coffeegreg** [comment] 2024-11-18 21:20
I understand that the 1test1` is in /etc and I ran it while in /etc. The result is ok. :+1: 
Please try again from another directory, providing the full path. What is the result ?

**Comment by rkerschn** [comment] 2024-11-18 21:23
May I ask what do you expect from the test1 program?

May I ask, don't you trust my findings?

**Comment by rkerschn** [comment] 2024-11-18 21:34
Since Alpine and OpenWrt are both based on musl and busybox, it should be fine, i guess.

I will check if FPC can compile against musl instead of glibc

**Comment by coffeegreg** [comment] 2024-11-18 21:36
Let's summarize. We did a good job and thanks to one link we managed to run Ytuner on OpenWRT. :clap:  In the process we discovered some interesting things and are wiser for new experiences. :+1: 
I hope YTuner will work well on your router. May the sound by with you... :speaker: :notes:

**Comment by rkerschn** [comment] 2024-11-18 21:39
To be honest, I would say that it requires workarounds. Either symbolic link or gcompat library.
Depending on the depth of glibc, it could be that YTuner will run flawlessly with musl libc.

I think the goal should be to compile against musl for Alpine Linux/OpenWrt

**Comment by TheBossME** [comment] 2024-11-18 21:41
Let's implement into the lovely AVM device FRITZ!Box 🤣🙏🙋‍♀️

**Comment by coffeegreg** [comment] 2024-11-18 21:52
I think I can close this record 68-comments issue. :eyes:

**Closed by coffeegreg** 2024-11-18 21:52 UTC
Labels: question, configuration
